[package]
name = "vbsp-to-gltf"
version = "0.1.0"
edition = "2021"


[dependencies]
miette = { version = "5.5.0", features = ["fancy"] }
vbsp = "0.4.0"
thiserror = "1.0.37"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-tree = "0.2.2"
vtf = "0.1.6"
vmt-parser = { version = "0.1", git = "https://github.com/icewind1991/vmt-parser" }
image = "0.23.14"
tf-asset-loader = { version = "0.1", features = ["bsp"] }
vmdl = { version = "*", git = "https://github.com/icewind1991/vmdl" }
clap = { version = "4.0.29", features = ["derive"] }
gltf-json = "=1.3.0"
gltf = "=1.3.0"
bytemuck = { version = "1.14.0", features = ["derive"] }

[profile.dev.package."*"]
opt-level = 2